name: few_cost_proxy
channels:
  - defaults
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - matplotlib-base=3.5.3
  - numpy=1.21.5
  - openssl=3.0.15
  - pandas=1.3.5
  - pillow=9.3.0
  - pip=22.3.1
  - python=3.7.1
  - seaborn=0.12.2
  - setuptools=65.6.3
  - sqlite=3.45.3
  - torchaudio=0.9.0
  - typing_extensions=4.4.0
  - wheel=0.38.4
  - pip:
      - configspace==0.7.1
      - cython==3.0.11
      - networkx==2.6.3
      - pyyaml==5.4.1
      - scikit-learn==1.0.2
      - scipy==1.4.1
      - torch==1.9.0+cu111
      - torchvision==0.10.0+cu111
      - tqdm==4.61.1
      - fasteners=0.19
      - netifaces=0.11.0
      - hpbandster=0.7.4
      - tensorboard_logger=0.1.0
      - protobuf==3.20
